### PR TITLE
Add support bell char and decode null char

### PR DESCRIPTION
**Pull request by lukemurray**
Hi, to avoid breaking changes in moving one of my old antler parsers I need to support the bell char and have the null char decoded.

This PR add support for that. There are probably other chars that are valid that might be worth adding.

Or perhaps a way to add extra valid chars to a string.

### CODE REVIEW

**Comment by sebastienros** [comment]
Can you update the tests that check this method? 
Do you know if these chars are common to most word strings like C#, JavaScript, json for instance? I can look it up.

**Comment by lukemurray** [comment]
Sorry to bother, just wondering if this is something you will consider merging or if there is anything else needed for the PR? Thanks.

**Comment by sebastienros** [comment]
Thanks, I had not seen the notification that the tests were added.

**Comment by sebastienros** [comment]
Do you need a new release with this change or are you using the source code directly?

**Comment by lukemurray** [comment]
Thanks. I'd love a release/nuget package.

**Comment by lukemurray** [comment]
Sorry, any chance of a 0.26 release with this?

Thanks!

**Pull request merged**
