### PR TITLE
Fix ScanHexEscape() & HexValue()

### PR DESCRIPTION
**Pull request by hishamco**

### CODE REVIEW

**Comment by sebastienros** [comment]
How is it better? At least it's not faster.

**Comment by hishamco** [comment]
First of all there's an issue in `HexValue()`  H is not a hexadecimal digit, second I used a compund if instead of nested if, if you see that's not faster - which is I don't know why - I can revert the other changes

**Comment by sebastienros** [comment]
Thanks, and I fixed the issues in another branch where I found more problems with these methods. For instance `\u` only accepts decimals, and `\x` might have one or two chars. I haven't handled all the cases still I think.

**Comment by hishamco** [comment]
I will try to test some cases too

**Pull request closed without merging**
