### PR TITLE
Pattern matching for chars

### PR DESCRIPTION
**Pull request by deanmarcussen**
Related to https://github.com/sebastienros/parlot/issues/22

Actually found myself just wanting to capture hex codes.

Figured that with `OneOrMany(Literals.Char(c => Character.IsHexDigit))` you can end up with a list of chars.

But this could also be applied the `Terms.Text` and use `ReadWhile` to return a `TextSpan`, which would be nicer.

Let me know

### CODE REVIEW

**Comment by sebastienros** [comment]
I will need to think about this. It doesn't look like Char should have a predicate. But I am wondering if the static helper should have it still, pointing to a new class. And maybe it should have a notion of size (min, max, exact) because it might make sense to read between 1-2 hex in some places, or read 4 chars followed by 2 in some other grammars. So this is about defining the exact literal we should expect (Char/Text) or a more custom one and return a TextSpan. So yeah, by writing it down, a new Literal that would have these concepts.

predicate
minSize: 1 by default
maxSize: 0 by default (unlimited)

Maybe call it `Literal.Predicate` ? Any better idea?

**Comment by deanmarcussen** [comment]
Yeah sounds good.
When I was thinking about whether it should be a new one, or fit into an existing, I thought of `Literal.Pattern` for `char` and `Literal.Patterns` for `TextSpan`. But ok with not having one that just returns a `char`... So could just be `Literal.Pattern` and return a `TextSpan`

**Comment by sebastienros** [comment]
good

**Comment by deanmarcussen** [comment]
`Literal.Pattern` with mins and maxes.

returns a `TextSpan`

no single `char` version - figured would just be extra noise.

**Comment by sebastienros** [comment]
I think this fixes #22

**Pull request merged**
